version: "3"
services:
  discord-rss-bot:
    image: ghcr.io/w3bprinz/k4.feeds:main
    container_name: discord-rss-bot
    environment:
      - DISCORD_TOKEN=dein_discord_bot_token
    volumes:
      - /mnt/user/appdata/discord-rss-bot/config.json:/app/config.json
      - /mnt/user/appdata/discord-rss-bot/.env:/app/.env
      - /mnt/user/appdata/discord-rss-bot/data:/app/data
    restart: unless-stopped
